/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface OracleTestInterface extends ethers.utils.Interface {
  functions: {
    "consult(address,uint32)": FunctionFragment;
    "getBlockStartingTickAndLiquidity(address)": FunctionFragment;
    "getChainedPrice(address[],int24[])": FunctionFragment;
    "getGasCostOfConsult(address,uint32)": FunctionFragment;
    "getGasCostOfGetQuoteAtTick(int24,uint128,address,address)": FunctionFragment;
    "getOldestObservationSecondsAgo(address)": FunctionFragment;
    "getQuoteAtTick(int24,uint128,address,address)": FunctionFragment;
    "getWeightedArithmeticMeanTick(tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "consult",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockStartingTickAndLiquidity",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainedPrice",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfConsult",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetQuoteAtTick",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOldestObservationSecondsAgo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteAtTick",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWeightedArithmeticMeanTick",
    values: [{ tick: BigNumberish; weight: BigNumberish }[]]
  ): string;

  decodeFunctionResult(functionFragment: "consult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBlockStartingTickAndLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfConsult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetQuoteAtTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOldestObservationSecondsAgo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteAtTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWeightedArithmeticMeanTick",
    data: BytesLike
  ): Result;

  events: {};
}

export class OracleTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: OracleTestInterface;

  functions: {
    consult(
      pool: string,
      secondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber] & {
        arithmeticMeanTick: number;
        harmonicMeanLiquidity: BigNumber;
      }
    >;

    getBlockStartingTickAndLiquidity(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[number, BigNumber]>;

    getChainedPrice(
      tokens: string[],
      ticks: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { syntheticTick: BigNumber }>;

    getGasCostOfConsult(
      pool: string,
      period: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getGasCostOfGetQuoteAtTick(
      tick: BigNumberish,
      baseAmount: BigNumberish,
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getOldestObservationSecondsAgo(
      pool: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & { secondsAgo: number; currentTimestamp: number }
    >;

    getQuoteAtTick(
      tick: BigNumberish,
      baseAmount: BigNumberish,
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { quoteAmount: BigNumber }>;

    getWeightedArithmeticMeanTick(
      observations: { tick: BigNumberish; weight: BigNumberish }[],
      overrides?: CallOverrides
    ): Promise<[number] & { arithmeticMeanWeightedTick: number }>;
  };

  consult(
    pool: string,
    secondsAgo: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber] & {
      arithmeticMeanTick: number;
      harmonicMeanLiquidity: BigNumber;
    }
  >;

  getBlockStartingTickAndLiquidity(
    pool: string,
    overrides?: CallOverrides
  ): Promise<[number, BigNumber]>;

  getChainedPrice(
    tokens: string[],
    ticks: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfConsult(
    pool: string,
    period: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getGasCostOfGetQuoteAtTick(
    tick: BigNumberish,
    baseAmount: BigNumberish,
    baseToken: string,
    quoteToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getOldestObservationSecondsAgo(
    pool: string,
    overrides?: CallOverrides
  ): Promise<
    [number, number] & { secondsAgo: number; currentTimestamp: number }
  >;

  getQuoteAtTick(
    tick: BigNumberish,
    baseAmount: BigNumberish,
    baseToken: string,
    quoteToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getWeightedArithmeticMeanTick(
    observations: { tick: BigNumberish; weight: BigNumberish }[],
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    consult(
      pool: string,
      secondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber] & {
        arithmeticMeanTick: number;
        harmonicMeanLiquidity: BigNumber;
      }
    >;

    getBlockStartingTickAndLiquidity(
      pool: string,
      overrides?: CallOverrides
    ): Promise<[number, BigNumber]>;

    getChainedPrice(
      tokens: string[],
      ticks: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfConsult(
      pool: string,
      period: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetQuoteAtTick(
      tick: BigNumberish,
      baseAmount: BigNumberish,
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOldestObservationSecondsAgo(
      pool: string,
      overrides?: CallOverrides
    ): Promise<
      [number, number] & { secondsAgo: number; currentTimestamp: number }
    >;

    getQuoteAtTick(
      tick: BigNumberish,
      baseAmount: BigNumberish,
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWeightedArithmeticMeanTick(
      observations: { tick: BigNumberish; weight: BigNumberish }[],
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    consult(
      pool: string,
      secondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBlockStartingTickAndLiquidity(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChainedPrice(
      tokens: string[],
      ticks: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfConsult(
      pool: string,
      period: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGasCostOfGetQuoteAtTick(
      tick: BigNumberish,
      baseAmount: BigNumberish,
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOldestObservationSecondsAgo(
      pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getQuoteAtTick(
      tick: BigNumberish,
      baseAmount: BigNumberish,
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWeightedArithmeticMeanTick(
      observations: { tick: BigNumberish; weight: BigNumberish }[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    consult(
      pool: string,
      secondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBlockStartingTickAndLiquidity(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainedPrice(
      tokens: string[],
      ticks: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfConsult(
      pool: string,
      period: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGasCostOfGetQuoteAtTick(
      tick: BigNumberish,
      baseAmount: BigNumberish,
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOldestObservationSecondsAgo(
      pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getQuoteAtTick(
      tick: BigNumberish,
      baseAmount: BigNumberish,
      baseToken: string,
      quoteToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWeightedArithmeticMeanTick(
      observations: { tick: BigNumberish; weight: BigNumberish }[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
